"""Tests for the spine rebuild pipeline.

The expensive steps need a population raster and a full geometry read, so
these cover what can be checked cheaply: the module imports, the paths it
writes to are the committed ones, and the two dry-run steps report without
touching anything. The guarantee that matters -- that the pipeline
reproduces the committed spine -- is asserted by
`test_admin_codes_audit.py::test_level_four_reproduces_exactly`.
"""

import pandas as pd
import pytest

from openplaces.io.admin_codes import build
from openplaces.io.admin_codes.registry import spine_path

# The population tables are derived aggregates that live in the data
# root, not in the package, so a machine without them (the CI runner)
# skips the checks that read them rather than failing on their absence.
needs_population = pytest.mark.skipif(
    not all(build.population_path(level).exists() for level in build.LEVELS),
    reason='population tables not built in this data root',
)


class TestPaths:
    def test_population_path_lives_outside_the_package(self):
        # These are derived aggregates, regenerated by build_population,
        # so they live with the data rather than in the package. The
        # spine tables themselves stay in `src/`: every other dataset is
        # keyed on them, which makes them a registry, not an aggregate.
        for level in build.LEVELS:
            assert build.population_path(level).parent != spine_path(level).parent

    @needs_population
    def test_population_tables_are_built(self):
        for level in build.LEVELS:
            path = build.population_path(level)
            assert path.exists(), f'level {level} population table is missing'

    @needs_population
    def test_every_level_is_fully_weighted(self):
        # The whole pipeline exists to make this true; a gap here means a
        # sibling group somewhere is tie-breaking on sort order.
        for level in build.LEVELS:
            spine = pd.read_csv(spine_path(level), dtype=str, keep_default_na=False)
            column = f'admin{level}_id'
            live = set(spine.loc[spine[column].str.strip() != '', column])
            weighted = set(pd.read_csv(build.population_path(level))['admin_id'])
            assert live <= weighted, (
                f'level {level}: {len(live - weighted):,} units unweighted'
            )

    @needs_population
    def test_no_estimated_weight_is_zero(self):
        # Zero loses every tie it enters, which is worse than unweighted
        # -- but only when the zero is a stand-in for a measurement that
        # could not be taken. A raster sum that came out at zero is
        # knowledge and stays.
        for level in build.LEVELS:
            table = pd.read_csv(build.population_path(level))
            estimated = table['source'].map(build.is_estimated)
            assert (table.loc[estimated, 'population'] > 0).all()

    def test_a_measured_zero_survives_repair(self):
        # The rule this encodes: openplaces may revise its own estimate,
        # never its own measurement.
        assert build.is_measured('ghs-pop-e2020')
        assert build.is_measured('ghs-pop-e2020-cousub')
        assert build.is_estimated('level-median')
        assert build.is_estimated('parent-split-equal')
        # A reviewed override is neither measured nor a guess, so a
        # placeholder deliberately weighted zero keeps its zero.
        assert not build.is_estimated('nameless-placeholder')
        assert not build.is_estimated('override-data-error')


class TestDryRuns:
    def test_resolving_references_reports_without_writing(self):
        # Run against the committed tree: after a settled re-mint nothing
        # should still name a retired identifier.
        assert build.resolve_stale_references(apply=False, verbose=False) == 0

    @needs_population
    def test_the_mint_is_a_fixed_point(self):
        # Re-deriving every identifier from the same weights must return
        # the same spine, or the identifiers are not reproducible.
        report = build.remint_spine(apply=False, verbose=False)
        for level, counts in report.items():
            assert counts['changed'] == 0, (
                f'level {level}: {counts["changed"]:,} identifiers would move'
            )
