"""Tests for the spine rebuild pipeline.

The expensive steps need a population raster and a full geometry read, so
these cover what can be checked cheaply: the module imports, the paths it
writes to are the committed ones, and the dry-run mint reports without
touching anything. The guarantee that matters -- that the pipeline
reproduces the committed spine -- is asserted by
`test_admin_codes_audit.py::test_weighted_derivation_reproduces_the_spine_exactly`
for levels 2 and 3, and by `test_the_mint_is_a_fixed_point` below for all.
"""

import pandas as pd
import pytest

from openplaces.io.admin_codes import build
from openplaces.io.admin_codes.registry import spine_path

# The population tables are derived aggregates that live in the data
# root, not in the package, so a machine without them (the CI runner)
# skips the checks that read them rather than failing on their absence.
needs_population = pytest.mark.skipif(
    not all(build.population_path(level).exists() for level in build.LEVELS),
    reason='population tables not built in this data root',
)


class TestPaths:
    def test_population_path_lives_outside_the_package(self):
        # These are derived aggregates, regenerated by build_population,
        # so they live with the data rather than in the package. The
        # spine tables themselves stay in `src/`: every other dataset is
        # keyed on them, which makes them a registry, not an aggregate.
        for level in build.LEVELS:
            assert build.population_path(level).parent != spine_path(level).parent

    @needs_population
    def test_population_tables_are_built(self):
        for level in build.LEVELS:
            path = build.population_path(level)
            assert path.exists(), f'level {level} population table is missing'

    @needs_population
    def test_every_level_is_fully_weighted(self):
        # The whole pipeline exists to make this true; a gap here means a
        # sibling group somewhere is tie-breaking on sort order.
        for level in build.LEVELS:
            spine = pd.read_csv(spine_path(level), dtype=str, keep_default_na=False)
            column = f'admin{level}_id'
            live = set(spine.loc[spine[column].str.strip() != '', column])
            weighted = set(pd.read_csv(build.population_path(level))['admin_id'])
            assert live <= weighted, (
                f'level {level}: {len(live - weighted):,} units unweighted'
            )

    @needs_population
    def test_no_estimated_weight_is_zero(self):
        # Zero loses every tie it enters, which is worse than unweighted
        # -- but only when the zero is a stand-in for a measurement that
        # could not be taken. A raster sum that came out at zero is
        # knowledge and stays.
        for level in build.LEVELS:
            table = pd.read_csv(build.population_path(level))
            estimated = table['source'].map(build.is_estimated)
            assert (table.loc[estimated, 'population'] > 0).all()

    def test_a_measured_zero_survives_repair(self):
        # The rule this encodes: openplaces may revise its own estimate,
        # never its own measurement.
        assert build.is_measured('ghs-pop-e2020')
        assert build.is_measured('ghs-pop-e2020-cousub')
        assert build.is_estimated('level-median')
        assert build.is_estimated('parent-split-equal')
        # A reviewed override is neither measured nor a guess, so a
        # placeholder deliberately weighted zero keeps its zero.
        assert not build.is_estimated('nameless-placeholder')
        assert not build.is_estimated('override-data-error')


class TestDryRuns:
    @needs_population
    def test_the_mint_is_a_fixed_point(self):
        # Re-deriving every identifier from the same weights must return
        # the same spine, or the identifiers are not reproducible.
        report = build.remint_spine(apply=False, verbose=False)
        for level, counts in report.items():
            assert counts['changed'] == 0, (
                f'level {level}: {counts["changed"]:,} identifiers would move'
            )


class TestPopulationCoverage:
    """Every polygon handed to the extractor comes back out weighted."""

    @pytest.fixture
    def one_unit_dropped(self, tmp_path, monkeypatch):
        """Three fabricated units, of which the extractor reports two.

        Returns the frame `build_population` writes for level 3.
        """
        import geopandas as gpd
        from shapely.geometry import box

        from openplaces import path as op_path
        from openplaces.geo import raster as op_raster

        units = ['XX-AA-AA', 'XX-AA-BB', 'XX-AA-CC']
        polygons = gpd.GeoDataFrame(
            {'resolved': units, 'geometry': [box(i, 0, i + 1, 1) for i in range(3)]},
            geometry='geometry',
            crs='EPSG:4326',
        )
        spine = pd.DataFrame({'admin3_id': units, 'name': list('ABC')})
        stats = pd.DataFrame(
            # The middle unit is missing outright, not NaN.
            {'resolved': ['XX-AA-AA', 'XX-AA-CC'], 'sum': [12.0, 34.0]}
        )
        raster = tmp_path / 'population.tif'
        raster.write_bytes(b'')
        written = tmp_path / 'level3-population.csv'

        monkeypatch.setattr(build, 'resolved_polygons', lambda level: polygons)
        monkeypatch.setattr(build, '_spine', lambda level: spine)
        monkeypatch.setattr(build, '_polygon_ids', lambda polygons: {})
        monkeypatch.setattr(build, 'population_path', lambda level: written)
        monkeypatch.setattr(
            build, 'spine_path', lambda level: tmp_path / 'admin-spine-2026_admin3.csv'
        )
        monkeypatch.setattr(op_path, 'resolve_raster_path', lambda name: raster)
        monkeypatch.setattr(
            op_raster,
            'zonal_stats_with_exactextract',
            lambda *args, **kwargs: stats,
        )
        return build.build_population(3, verbose=False)

    def test_a_unit_the_extractor_skips_is_still_weighted(self, one_unit_dropped):
        # Without the reindex the row is absent, so the gap filler hands
        # it the level median and an uninhabited unit outranks real
        # towns in the mint.
        assert set(one_unit_dropped['admin_id']) == {
            'XX-AA-AA',
            'XX-AA-BB',
            'XX-AA-CC',
        }

    def test_a_skipped_unit_is_weighted_zero_not_null(self, one_unit_dropped):
        skipped = one_unit_dropped.set_index('admin_id').loc['XX-AA-BB']
        assert skipped['population'] == 0
        assert skipped['source'] == 'ghs-pop-e2020'

    def test_the_measured_units_keep_their_sums(self, one_unit_dropped):
        measured = one_unit_dropped.set_index('admin_id')['population']
        assert measured['XX-AA-AA'] == 12
        assert measured['XX-AA-CC'] == 34
