"""The docs validation-table generator, on fabricated reports only."""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pandas as pd
import pytest

from openplaces.io.curator.validation import (
    write_confusion_report,
    write_year_agreement_report,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
GENERATOR_PATH = REPO_ROOT / 'docs' / '_ext' / 'generate_validation_tables.py'


@pytest.fixture(scope='module')
def generator():
    spec = importlib.util.spec_from_file_location('gvt', GENERATOR_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _report(folder):
    # 3x3 fabricated counts: rows A 8/2/0, B 1/9/0, C 0/0/10, plus two
    # abstentions on C.
    truth, predicted = [], []
    for reference, counts in (('A', (8, 2, 0)), ('B', (1, 9, 0)), ('C', (0, 0, 10))):
        for column, n in zip('ABC', counts, strict=True):
            truth += [reference] * n
            predicted += [column] * n
    truth += ['C', 'C']
    predicted += [None, None]
    return write_confusion_report(
        pd.Series(truth),
        {'final_vote': pd.Series(predicted)},
        ['A', 'B', 'C'],
        folder,
        'demo',
        strata={'county': pd.Series(['X01'] * 16 + ['X02'] * 16)},
        reference='fabricated',
    )


def test_fragment_renders_the_matrix_with_both_accuracies(generator, tmp_path):
    region_dir = tmp_path / 'data' / 'region-one'
    paths = _report(region_dir)

    fragment = generator.render_snapshot(
        paths['confusion'], generated_dir=tmp_path / 'out', images=False
    )
    text = fragment.read_text(encoding='utf-8')

    assert text.startswith('.. Generated by docs/_ext/generate_validation_tables.py')
    assert 'do not edit' in text.splitlines()[1]
    expected_matrix = generator.list_table(
        [
            'reference (rows) / predicted (columns)',
            'A',
            'B',
            'C',
            '(other class)',
            'No class',
            "producer's accuracy (recall)",
        ],
        [
            ['A', '**8**', '2', '0', '0', '0', '0.800'],
            ['B', '1', '**9**', '0', '0', '0', '0.900'],
            ['C', '0', '0', '**10**', '0', '2', '1.000'],
            [
                "consumer's accuracy (precision)",
                '0.889',
                '0.818',
                '1.000',
                '',
                '',
                'overall 0.900, kappa 0.850',
            ],
        ],
        'Confusion matrix, final_vote',
    )
    assert '\n'.join(expected_matrix) in text
    assert '.. list-table:: By county, final_vote' in text
    assert '.. list-table:: Per class, pooled' in text


def test_regeneration_is_deterministic(generator, tmp_path):
    paths = _report(tmp_path / 'data' / 'region-one')
    first = generator.render_snapshot(
        paths['confusion'], generated_dir=tmp_path / 'a', images=False
    ).read_text(encoding='utf-8')
    second = generator.render_snapshot(
        paths['confusion'], generated_dir=tmp_path / 'b', images=False
    ).read_text(encoding='utf-8')
    assert first == second


def test_year_report_renders_its_bins(generator, tmp_path):
    paths = write_year_agreement_report(
        pd.Series([2000] * 12),
        {'inventory': pd.Series([2000] * 10 + [2003, None])},
        tmp_path / 'data' / 'region-one',
        'years',
    )
    text = generator.render_snapshot(
        paths['confusion'], generated_dir=tmp_path / 'out', images=False
    ).read_text(encoding='utf-8')
    assert '.. list-table:: Year built agreement' in text
    assert '     - 0.909' in text


def test_heatmap_is_written(generator, tmp_path):
    paths = _report(tmp_path / 'data' / 'region-one')
    generator.render_snapshot(
        paths['confusion'],
        generated_dir=tmp_path / 'out',
        image_dir=tmp_path / 'img',
    )
    assert (tmp_path / 'img' / 'region-one_demo.png').stat().st_size > 0


def test_committed_fragments_match_their_snapshots(generator, tmp_path):
    """A hand edit to a generated fragment fails here."""
    for snapshot in sorted(generator.SNAPSHOT_DIR.glob('*/*_confusion.csv')):
        region = snapshot.parent.name
        name = snapshot.name.removesuffix('_confusion.csv')
        committed = generator.GENERATED_DIR / f'{region}_{name}.rst'
        regenerated = generator.render_snapshot(
            snapshot, generated_dir=tmp_path, images=False
        )
        text = regenerated.read_text(encoding='utf-8')
        image = f'/_static/images/validation/{region}_{name}.png'
        # Rendered without the image here; the committed one has it.
        expected = committed.read_text(encoding='utf-8')
        expected = expected.replace(
            f'\n\n.. image:: {image}\n   :alt: Heatmap of {name}, {region}', ''
        )
        assert text == expected, committed
