"""CHEER-specific configuration for the occupancy validation notebooks.

The linkage and scoring themselves are generic and live in
:mod:`openplaces.io.curator.validation`. Everything that is specific to
the CHEER summer-scholars survey -- which counties it covers, where the
cleaned survey CSV lives, which curated recipe it validates, and how the
inventory's Multi-Family bands collapse onto the survey's three classes
-- is collected here so neither notebook hardcodes it.

This module deliberately lives beside the notebooks rather than in
``src/openplaces``: it names counties, a survey vintage, and a recipe, and
geography-specific configuration does not belong in the package. It is
equally deliberately not in ``scripts/``, which holds only the artifacts
generated by ``openplaces.flow.convert_to_script`` and is not tracked.

The survey CSV it reads is produced by
``notebooks/02_ingest/footprints/prepare_cheer_ground_truth.ipynb``.
"""

from __future__ import annotations

from pathlib import Path

import geopandas as gpd
import pandas as pd

import openplaces as op
from openplaces.core.schema import Entity
from openplaces.io.curator.validation import (
    classify_validation_result,
    link_points_to_entities,
    score_classification,
    summarize_sources,
)
from openplaces.path import cache_path, external_dir

RECIPE_ID = 'US_footprint-cheer-2026'

# The survey classes, in the order the baseline table reports them.
CLASSES = ('Single-Family', 'Multi-Family', 'Manufactured Home')

# The survey records one residential class per building; the inventory
# resolves Multi-Family into height bands. Collapse the bands so the two
# vocabularies are comparable, rather than scoring every apartment block
# as a miss.
COLLAPSE = {
    'Low-Rise Multi-Family': 'Multi-Family',
    'Mid-Rise Multi-Family': 'Multi-Family',
    'High-Rise Multi-Family': 'Multi-Family',
}

# Stands in for "no class" when two class columns are compared, so a
# missing value on either side compares equal to itself and unequal to
# every real class. Any string no ruleset can emit works; this one is
# obviously not a class name.
_NO_CLASS = '<none>'

# Classes that describe exactly one dwelling. Manufactured Home counts
# as single here: a double or triple wide is one home, not one per
# section.
SINGLE_DWELLING_CLASSES = ('Single-Family', 'Manufactured Home')

# Street View 'right-click for coordinates' pins routinely land just off
# the roof polygon, so point-in-polygon undercounts badly (as low as 33%
# in Brunswick). 15 m clears the observed pin offsets (Brunswick median
# 1.7 m, 98% under 20 m) while staying tight enough not to grab the
# neighbouring building.
MAX_DIST_M = 15
STREET_THRESHOLD = 80.0

# A house and its garage share one address, so an address match alone
# often leaves several footprints tied. The survey only ever labels
# habitable buildings, so break those ties toward the parcel's primary
# structure -- without this the pick falls to row order and lands on a
# shed often enough to cost Single-Family several points of F1.
PREFER_COLUMN = 'priority_on_parcel'
PREFER_VALUES = ('primary', 'unknown')

_SURVEY_ENTITY = Entity('footprint', 'cheer', 'summerscholars2026')
_RECIPE_ENTITY = Entity('footprint', 'cheer', '2026')

# The cleaned survey CSV, written by prepare_cheer_ground_truth.
GROUND_TRUTH_PATH = (
    external_dir('US-NC', entity=_SURVEY_ENTITY)
    / 'US-NC_footprint-cheer-summerscholars.csv'
)

# Survey-derived outputs are third-party-derived, so they belong in the
# cache tree and never beside the recipe in the repository.
VALIDATION_DIR = cache_path('US', entity=_RECIPE_ENTITY, as_dir=True)
BASELINE_PATH = cache_path(
    'US',
    entity=_RECIPE_ENTITY,
    filename='occupancy-baseline',
    default_extension='csv',
)
LINKED_PATH = cache_path('US', entity=_RECIPE_ENTITY, filename='validation-footprints')

# The accepted run's per-point predictions, which is what makes the gate a
# paired test rather than a comparison of two independent point estimates.
# Deliberately narrow: the survey row's own coordinates, the hand label and
# the predicted class, and nothing else. The linked frame it comes from
# carries addresses, and this file exists to be read by whoever is judging a
# change, so it must not.
BASELINE_PREDICTIONS_PATH = cache_path(
    'US',
    entity=_RECIPE_ENTITY,
    filename='occupancy-baseline-predictions',
    default_extension='csv',
)

# Identifies a surveyed building by where it sits in the source workbook,
# which no pipeline change can move. Footprint ids cannot serve: several
# survey points legitimately land on one footprint (1,370 points on 1,231
# footprints), so they are not a key.
PREDICTION_KEY = ['source_sheet', 'source_row']

# Rulesets stored beside the curate recipe, used to rebuild the class
# columns `order_columns.drop` removes from published output.
CLASS_MAP = 'occupancy-class-map.csv'
KEYWORD_RULESET = 'parcel-occupancy-keywords.csv'

# Evidence columns on the linked frame, labelled as the baseline's
# `source` column reports them. Each is scored on its own so a change
# that improves the vote by discarding a good input stays visible.
# Overture is not one of these: it is derived, see `source_values`.
SOURCE_COLUMNS = {
    'final_vote': 'predicted',
    'nsi': 'occupancy_type_nsi_class_inv',
    'fema': 'occupancy_type_fema_class_inv',
    'keyword': 'occupancy_keyword_class_inv',
    'parcel': 'occupancy_type_parcel_inv',
}

# Suffix `link_ground_truth` puts on every curated column, to keep them
# apart from the survey's own. The specs below name the curated columns
# without it, so the permit notebook -- which joins curated output under
# its own names -- can read the same specs.
INVENTORY_SUFFIX = '_inv'

# The curate recipe's `order_columns.drop` removes the derived
# `occupancy_type_nsi_class`, `occupancy_type_fema_class` and
# `occupancy_keyword_class` columns from published output -- they are
# vote-scoring intermediates, not attributes. They are reconstructible from
# the raw evidence through the same ruleset the vote used, so scoring falls
# back to that rather than silently dropping those blocks (which cost the
# baseline 8 of its 20 rows, unnoticed, because `source_values` skipped
# absent columns without complaint).
DERIVED_SOURCE_COLUMNS = {
    'nsi': {'column': 'occupancy_type_building_nsi'},
    'fema': {'column': 'group_footprint_fema'},
    'keyword': {
        'column': 'use_group_combined_parcel',
        'ruleset': KEYWORD_RULESET,
        # The curate step sets `reviewed_only`, so the reconstruction must
        # too: without it the unreviewed rules (MODULAR, bare MH, COMMERCIAL,
        # RETAIL) would put classes on rows the vote never saw a keyword
        # claim for, and the reconstructed column would score a column that
        # never existed.
        'reviewed_only': True,
    },
}

# Overture carries a dwelling count, not a class. Two or more dwellings
# means Multi-Family; anything else, including no count at all, reads as
# Single-Family. That default is why Overture scores near-perfect recall
# on Single-Family and cannot score Manufactured Home at all -- it never
# declines to answer, so its Single-Family precision is what to read.
OVERTURE_COLUMN = 'n_dwellings_overture_inv'


# The Shovels permit validation parquets, one footprint/parcel pair per
# county, written by the shovels worktree. Permits are the second
# out-of-band reference after the survey: not NSI-derived, not
# parcel-derived, and not baked into the curated output.
PERMIT_DIR = (
    external_dir('US-NC', entity=Entity('property', 'shovels', '2026')) / 'validation'
)

# Confidence tiers for permit occupancy evidence, strongest first. The
# strong three are what the accuracy tables score on; `4_addr_weak` is a
# single uncorroborated address match and is reported but not scored.
PERMIT_STRONG_TIERS = ('1_id_strong', '2_id_weak', '3_addr_strong')


def permit_counties() -> list[str]:
    """Counties with a complete footprint+parcel permit pair on disk.

    An incomplete pair means a mid-write county, not a county without
    permits, so it is skipped rather than read.
    """
    import re

    kinds: dict[str, set[str]] = {}
    for path in sorted(PERMIT_DIR.glob('US-NC-*_occupancy_validation.parquet')):
        match = re.match(
            r'(US-NC-\w\w)_(footprint|parcel)_occupancy_validation', path.stem
        )
        if match:
            kinds.setdefault(match.group(1), set()).add(match.group(2))
    return sorted(c for c, k in kinds.items() if k == {'footprint', 'parcel'})


def load_permits(admin_id: str) -> pd.DataFrame | None:
    """Load one county's footprint-level permit evidence, or None."""
    path = PERMIT_DIR / f'{admin_id}_footprint_occupancy_validation.parquet'
    if not path.exists():
        return None
    frame = pd.read_parquet(path)
    frame.index.name = 'footprint_id'
    return frame


def permit_tier(frame: pd.DataFrame) -> pd.Series:
    """Confidence tier for permit occupancy evidence, high to low.

    Two things separate a strong claim from a weak one: how the permits
    reached the footprint (``parcel_id_local`` beats an address match) and
    whether they agree (a unanimous mode over at least two occupancy-bearing
    permits beats a single uncorroborated one).

    Parameters
    ----------
    frame : pandas.DataFrame
        One county's permit evidence, as returned by :func:`load_permits`.

    Returns
    -------
    pandas.Series
        One of ``1_id_strong``, ``2_id_weak``, ``3_addr_strong``,
        ``4_addr_weak``, or ``none`` where no permit names an occupancy.
    """
    n_occupancy = pd.to_numeric(frame['n_permits_with_occupancy_type'], errors='coerce')
    unanimous = frame['occupancy_type_mode_pct'].ge(0.999) & n_occupancy.ge(2)
    by_id = frame['matched_via'].eq('parcel_id_local')
    spoke = frame['occupancy_type_mode'].notna()
    tier = pd.Series('none', index=frame.index)
    tier[spoke & ~by_id & ~unanimous] = '4_addr_weak'
    tier[spoke & ~by_id & unanimous] = '3_addr_strong'
    tier[spoke & by_id & ~unanimous] = '2_id_weak'
    tier[spoke & by_id & unanimous] = '1_id_strong'
    return tier


def _survey_counties() -> tuple[str, ...]:
    """Counties present in the survey CSV, sorted.

    Discovered rather than hardcoded: the survey's own county column is
    derived by spatially joining each pin against the NC county polygons,
    so it already reflects the pins that landed outside their declared
    tab (the Robeson tab carries a copy-pasted Beaufort coordinate).
    """
    if not GROUND_TRUTH_PATH.exists():
        raise FileNotFoundError(
            f'CHEER survey CSV not found at {GROUND_TRUTH_PATH}. Run '
            'notebooks/02_ingest/footprints/prepare_cheer_ground_truth.ipynb '
            'to regenerate it from the source workbook.'
        )
    admin_ids = pd.read_csv(GROUND_TRUTH_PATH, usecols=['admin_id'])['admin_id']
    return tuple(sorted(admin_ids.dropna().unique()))


COUNTIES = _survey_counties()


def load_ground_truth(counties: tuple[str, ...] | None = None) -> pd.DataFrame:
    """Load the cleaned survey points, optionally restricted to *counties*.

    Parameters
    ----------
    counties : tuple of str, optional
        Admin IDs to keep. Defaults to every county in the survey.

    Returns
    -------
    pandas.DataFrame
        One row per surveyed building, carrying the hand-assigned
        ``occupancy_type_canonical``, the pinned ``lat``/``lon``, and the
        parsed ``address_number``/``address_street`` matching keys. Rows
        without a resolved county are dropped: they cannot be linked
        against a county's curated output.
    """
    points = pd.read_csv(GROUND_TRUTH_PATH)
    points = points[points['admin_id'].notna()]
    if counties:
        points = points[points['admin_id'].isin(tuple(counties))]
    return points.reset_index(drop=True)


def collapse_bands(values: pd.Series) -> pd.Series:
    """Map the inventory's Multi-Family height bands onto Multi-Family."""
    return values.astype(object).replace(COLLAPSE)


def class_from_ruleset(
    terms: pd.Series,
    ruleset: str = CLASS_MAP,
    *,
    reviewed_only: bool = False,
) -> pd.Series | None:
    """Reconstruct an occupancy class column from raw evidence.

    Applies the same ordered ruleset the curate vote used, so a
    reconstructed column scores identically to the dropped one.

    Parameters
    ----------
    terms : pandas.Series
        Raw label text the class column was derived from.
    ruleset : str, optional
        Filename of the ruleset CSV beside the curate recipe. Defaults to
        :data:`CLASS_MAP`, the occupancy vocabulary nsi and fema use.
    reviewed_only : bool, optional
        Keep only matches whose winning rule is marked reviewed, mirroring
        the recipe's own ``reviewed_only`` flag. Nulling unreviewed matches
        after the fact -- rather than dropping those rules up front -- is
        deliberate: pre-filtering would let a term fall through to a later
        reviewed rule and assert a class the vote never saw.

    Returns
    -------
    pandas.Series or None
        The reconstructed class column, or None when the ruleset cannot be
        located, leaving the caller to omit that source rather than fail.
    """
    from types import SimpleNamespace

    from openplaces.io.curator.occupancy import load_ruleset, match_ruleset
    from openplaces.recipe import get_recipe_by_id

    try:
        # load_ruleset only reads `state.recipe`, so a stand-in carrying the
        # recipe is enough; building a real CurateState here would mean
        # loading an entity we do not need.
        state = SimpleNamespace(recipe=get_recipe_by_id(RECIPE_ID))
        rules = load_ruleset(state, ruleset)
    except (FileNotFoundError, KeyError):
        return None
    proposal, reviewed = match_ruleset(terms.astype(object), rules)
    if reviewed_only:
        proposal = proposal.where(reviewed)
    return proposal


def check_baseline_coverage(table: pd.DataFrame, baseline: pd.DataFrame) -> None:
    """Fail loudly when a baseline row finds no counterpart in *table*.

    The gate merges on (source, class). A source missing from *table* drops
    its baseline rows from the comparison silently, so the gate passes while
    scoring fewer sources than it claims to. That is exactly what happened
    when `order_columns` began dropping the nsi and fema class columns.
    """
    expected = set(map(tuple, baseline[['source', 'class']].to_numpy()))
    actual = set(map(tuple, table[['source', 'class']].to_numpy()))
    missing = sorted(expected - actual)
    if missing:
        raise SystemExit(
            f'FAIL: {len(missing)} baseline row(s) had no counterpart to '
            f'compare against, so the gate would have scored only '
            f'{len(actual)} of {len(expected)} rows: {missing}'
        )


def source_values(linked: pd.DataFrame) -> dict[str, pd.Series]:
    """The vote and each input it arbitrates, on the survey's vocabulary.

    Parameters
    ----------
    linked : pandas.DataFrame
        Output of :func:`link_ground_truth`.

    Returns
    -------
    dict of str to pandas.Series
        Source label to comparable class values, height bands collapsed.
    """
    values = {
        label: collapse_bands(linked[column])
        for label, column in SOURCE_COLUMNS.items()
        if column in linked.columns
    }
    for label, spec in DERIVED_SOURCE_COLUMNS.items():
        column = spec['column'] + INVENTORY_SUFFIX
        if label in values or column not in linked.columns:
            continue
        derived = class_from_ruleset(
            linked[column],
            spec.get('ruleset', CLASS_MAP),
            reviewed_only=spec.get('reviewed_only', False),
        )
        if derived is not None:
            values[label] = collapse_bands(derived)
    if OVERTURE_COLUMN in linked.columns:
        dwellings = pd.to_numeric(linked[OVERTURE_COLUMN], errors='coerce')
        values['overture'] = pd.Series(
            [
                'Multi-Family' if n >= 2 else 'Single-Family'
                for n in dwellings.fillna(0)
            ],
            index=linked.index,
            dtype=object,
        )
    return values


def link_ground_truth(
    counties: tuple[str, ...] | None = None,
    *,
    verbose: bool = False,
    save: bool = True,
) -> gpd.GeoDataFrame:
    """Link the survey points to curated footprints, county by county.

    Address identity is tried before proximity (see
    :func:`~openplaces.io.curator.validation.link_points_to_entities`),
    because the nearest footprint to a survey pin is very often a shed or
    the neighbour's house.

    Parameters
    ----------
    counties : tuple of str, optional
        Admin IDs to link. Defaults to :data:`COUNTIES`.
    verbose : bool, optional
        Report per-county linkage counts.
    save : bool, optional
        Write the linked frame to :data:`LINKED_PATH` (parquet, plus a CSV
        sidecar for review). Default True.

    Returns
    -------
    geopandas.GeoDataFrame
        One row per linked point: the survey columns, every curated column
        suffixed ``_inv``, ``matched_by``, and the derived comparison
        columns ``predicted``, ``is_single_dwelling``, ``validation_result``,
        ``occupancy_type_conflict_sources`` and ``sources_disagree``. The
        geometry is the matched footprint, not the survey pin.
    """
    counties = tuple(counties) if counties else COUNTIES
    frames = []
    crs = None
    for admin_id in counties:
        points = load_ground_truth((admin_id,))
        if points.empty:
            continue
        entities = op.get_entities(RECIPE_ID, admin_id, geom=True, missing='ignore')
        if entities is None or entities.empty:
            if verbose:
                print(f'{admin_id}: no curated output on disk, skipped')
            continue
        crs = entities.crs
        # reset_index carries footprint_id through as a column, so the
        # permit notebook can join on an ID that is stable across
        # branches.
        linked = link_points_to_entities(
            points,
            entities.reset_index(),
            max_distance_m=MAX_DIST_M,
            street_threshold=STREET_THRESHOLD,
            admin1_id='US-NC',
            prefer_column=PREFER_COLUMN,
            prefer_values=PREFER_VALUES,
        )
        if linked.empty:
            if verbose:
                print(f'{admin_id}: {len(points)} points, none linked')
            continue
        if verbose:
            by_route = linked['matched_by'].value_counts()
            print(
                f'{admin_id}: {len(linked)}/{len(points)} points linked '
                f'(address {by_route.get("address", 0)}, '
                f'distance {by_route.get("distance", 0)})'
            )
        frames.append(linked)

    if not frames:
        return gpd.GeoDataFrame()

    linked = pd.concat(frames, ignore_index=True)
    linked['predicted'] = collapse_bands(linked['occupancy_type_inv'])
    linked['is_single_dwelling'] = linked['occupancy_type_canonical'].isin(
        SINGLE_DWELLING_CLASSES
    )
    linked['validation_result'] = classify_validation_result(
        linked['occupancy_type_canonical'], linked['predicted']
    )

    sources = source_values(linked)
    linked['occupancy_type_conflict_sources'] = summarize_sources(
        {'ground_truth': linked['occupancy_type_canonical'], **sources}
    )
    # Flag the rows worth reading by hand: any input that spoke and was
    # overruled. Rows where every source agrees need no adjudication.
    # Both sides are compared through a sentinel rather than directly:
    # `occupancy_type` is a nullable string column, so a row the vote
    # declined to classify makes `ne` return pd.NA instead of a bool, and
    # `|=` on that raises. Reading a missing vote as a disagreement is the
    # intended answer, not a convenience -- an input that spoke while the
    # vote stayed silent was still discarded, which is exactly the case
    # this flag exists to surface.
    predicted = linked['predicted'].astype(object).fillna(_NO_CLASS)
    disagree = pd.Series(False, index=linked.index)
    for label, values in sources.items():
        if label == 'final_vote':
            continue
        values = values.astype(object)
        disagree |= values.notna() & values.fillna(_NO_CLASS).ne(predicted)
    linked['sources_disagree'] = disagree

    # link_points_to_entities returns a plain DataFrame, so the matched
    # footprint arrives as a CRS-less object column; restore it from the
    # entities it came from.
    linked = gpd.GeoDataFrame(
        linked.drop(columns='geometry_inv'),
        geometry=gpd.GeoSeries(linked['geometry_inv'], crs=crs),
    )
    if save:
        VALIDATION_DIR.mkdir(parents=True, exist_ok=True)
        linked.to_parquet(LINKED_PATH)
        linked.drop(columns='geometry').to_csv(
            LINKED_PATH.with_suffix('.csv'), index=False
        )
        if verbose:
            print(f'wrote {len(linked)} linked points to {LINKED_PATH}')
    return linked


def save_baseline_predictions(linked: pd.DataFrame, path=None) -> Path:
    """Write the accepted run's per-point predictions for the paired gate.

    Parameters
    ----------
    linked : pandas.DataFrame
        Output of :func:`link_ground_truth`.
    path : path-like, optional
        Destination. Defaults to :data:`BASELINE_PREDICTIONS_PATH`.

    Returns
    -------
    pathlib.Path
        Where it was written.
    """
    path = Path(path or BASELINE_PREDICTIONS_PATH)
    path.parent.mkdir(parents=True, exist_ok=True)
    columns = [*PREDICTION_KEY, 'occupancy_type_canonical', 'predicted']
    linked[columns].to_csv(path, index=False)
    return path


def load_baseline_predictions(path=None) -> pd.DataFrame:
    """Read the baseline predictions written by :func:`save_baseline_predictions`."""
    path = Path(path or BASELINE_PREDICTIONS_PATH)
    if not path.exists():
        raise FileNotFoundError(
            f'No baseline predictions at {path}. Run this notebook once with '
            '--write_baseline to record the accepted run before gating '
            'against it.'
        )
    return pd.read_csv(path)


def align_to_baseline(linked: pd.DataFrame, baseline: pd.DataFrame):
    """Line the current run's predictions up with the baseline's, per point.

    Returns the points both runs share. Points only one of them has are
    reported rather than silently dropped: the survey and the linkage both
    move over time, and a gate that quietly scored a different set of
    buildings than the baseline did would be comparing two things.

    Parameters
    ----------
    linked : pandas.DataFrame
        Output of :func:`link_ground_truth`.
    baseline : pandas.DataFrame
        Output of :func:`load_baseline_predictions`.

    Returns
    -------
    tuple
        ``(truth, baseline_predicted, current_predicted, report)`` -- three
        aligned Series and a dict of ``n_shared``/``n_baseline_only``/
        ``n_current_only``.
    """
    key = PREDICTION_KEY
    current = linked[[*key, 'occupancy_type_canonical', 'predicted']].copy()
    merged = current.merge(
        baseline, on=key, how='inner', suffixes=('', '_base'), validate='1:1'
    )
    report = {
        'n_shared': len(merged),
        'n_baseline_only': len(baseline) - len(merged),
        'n_current_only': len(current) - len(merged),
    }
    # The hand label is the survey's, so it should not move; if it has, the
    # current run's label wins and the count says how often that happened.
    report['n_truth_changed'] = int(
        merged['occupancy_type_canonical']
        .astype(object)
        .ne(merged['occupancy_type_canonical_base'].astype(object))
        .sum()
    )
    return (
        merged['occupancy_type_canonical'],
        merged['predicted_base'],
        merged['predicted'],
        report,
    )


def score_sources(linked: pd.DataFrame) -> pd.DataFrame:
    """Score the vote and each of its inputs against the survey labels.

    Scoring the inputs alongside the vote is what makes the baseline
    readable: a vote that scores worse than one of its own inputs on a
    class is discarding evidence, which a single-column score cannot show.

    Parameters
    ----------
    linked : pandas.DataFrame
        Output of :func:`link_ground_truth`.

    Returns
    -------
    pandas.DataFrame
        :func:`~openplaces.io.curator.validation.score_classification`
        output for each source, with a leading ``source`` column.
    """
    tables = []
    for label, values in source_values(linked).items():
        table = score_classification(
            linked['occupancy_type_canonical'], values, list(CLASSES)
        )
        table.insert(0, 'source', label)
        tables.append(table)
    return pd.concat(tables, ignore_index=True)
