"""CHEER-specific configuration for the occupancy validation notebooks.

The linkage and scoring themselves are generic and live in
:mod:`openplaces.io.curator.validation`. Everything that is specific to
the CHEER summer-scholars survey -- which counties it covers, where the
cleaned survey CSV lives, which curated recipe it validates, and how the
inventory's Multi-Family bands collapse onto the survey's three classes
-- is collected here so neither notebook hardcodes it.

This module deliberately lives beside the notebooks rather than in
``src/openplaces``: it names counties, a survey vintage, and a recipe, and
geography-specific configuration does not belong in the package. It is
equally deliberately not in ``scripts/``, which holds only the artifacts
generated by ``openplaces.flow.convert_to_script`` and is not tracked.

The survey CSV it reads is produced by
``notebooks/02_ingest/footprints/prepare_cheer_ground_truth.ipynb``.
"""

from __future__ import annotations

import geopandas as gpd
import pandas as pd

import openplaces as op
from openplaces.core.schema import Entity
from openplaces.io.curator.validation import (
    classify_validation_result,
    link_points_to_entities,
    score_classification,
    summarize_sources,
)
from openplaces.path import cache_path, external_dir

RECIPE_ID = 'US_footprint-cheer-2026'

# The survey classes, in the order the baseline table reports them.
CLASSES = ('Single-Family', 'Multi-Family', 'Manufactured Home')

# The survey records one residential class per building; the inventory
# resolves Multi-Family into height bands. Collapse the bands so the two
# vocabularies are comparable, rather than scoring every apartment block
# as a miss.
COLLAPSE = {
    'Low-Rise Multi-Family': 'Multi-Family',
    'Mid-Rise Multi-Family': 'Multi-Family',
    'High-Rise Multi-Family': 'Multi-Family',
}

# Classes that describe exactly one dwelling. Manufactured Home counts
# as single here: a double or triple wide is one home, not one per
# section.
SINGLE_DWELLING_CLASSES = ('Single-Family', 'Manufactured Home')

# Street View 'right-click for coordinates' pins routinely land just off
# the roof polygon, so point-in-polygon undercounts badly (as low as 33%
# in Brunswick). 15 m clears the observed pin offsets (Brunswick median
# 1.7 m, 98% under 20 m) while staying tight enough not to grab the
# neighbouring building.
MAX_DIST_M = 15
STREET_THRESHOLD = 80.0

# A house and its garage share one address, so an address match alone
# often leaves several footprints tied. The survey only ever labels
# habitable buildings, so break those ties toward the parcel's primary
# structure -- without this the pick falls to row order and lands on a
# shed often enough to cost Single-Family several points of F1.
PREFER_COLUMN = 'priority_on_parcel'
PREFER_VALUES = ('primary', 'unknown')

_SURVEY_ENTITY = Entity('footprint', 'cheer', 'summerscholars2026')
_RECIPE_ENTITY = Entity('footprint', 'cheer', '2026')

# The cleaned survey CSV, written by prepare_cheer_ground_truth.
GROUND_TRUTH_PATH = (
    external_dir('US-NC', entity=_SURVEY_ENTITY)
    / 'US-NC_footprint-cheer-summerscholars.csv'
)

# Survey-derived outputs are third-party-derived, so they belong in the
# cache tree and never beside the recipe in the repository.
VALIDATION_DIR = cache_path('US', entity=_RECIPE_ENTITY, as_dir=True)
BASELINE_PATH = cache_path(
    'US',
    entity=_RECIPE_ENTITY,
    filename='occupancy-baseline',
    default_extension='csv',
)
LINKED_PATH = cache_path('US', entity=_RECIPE_ENTITY, filename='validation-footprints')

# Evidence columns on the linked frame, labelled as the baseline's
# `source` column reports them. Each is scored on its own so a change
# that improves the vote by discarding a good input stays visible.
# Overture is not one of these: it is derived, see `source_values`.
SOURCE_COLUMNS = {
    'final_vote': 'predicted',
    'nsi': 'occupancy_type_nsi_class_inv',
    'fema': 'occupancy_type_fema_class_inv',
    'parcel': 'occupancy_type_parcel_inv',
}

# Overture carries a dwelling count, not a class. Two or more dwellings
# means Multi-Family; anything else, including no count at all, reads as
# Single-Family. That default is why Overture scores near-perfect recall
# on Single-Family and cannot score Manufactured Home at all -- it never
# declines to answer, so its Single-Family precision is what to read.
OVERTURE_COLUMN = 'n_dwellings_overture_inv'


def _survey_counties() -> tuple[str, ...]:
    """Counties present in the survey CSV, sorted.

    Discovered rather than hardcoded: the survey's own county column is
    derived by spatially joining each pin against the NC county polygons,
    so it already reflects the pins that landed outside their declared
    tab (the Robeson tab carries a copy-pasted Beaufort coordinate).
    """
    if not GROUND_TRUTH_PATH.exists():
        raise FileNotFoundError(
            f'CHEER survey CSV not found at {GROUND_TRUTH_PATH}. Run '
            'notebooks/02_ingest/footprints/prepare_cheer_ground_truth.ipynb '
            'to regenerate it from the source workbook.'
        )
    admin_ids = pd.read_csv(GROUND_TRUTH_PATH, usecols=['admin_id'])['admin_id']
    return tuple(sorted(admin_ids.dropna().unique()))


COUNTIES = _survey_counties()


def load_ground_truth(counties: tuple[str, ...] | None = None) -> pd.DataFrame:
    """Load the cleaned survey points, optionally restricted to *counties*.

    Parameters
    ----------
    counties : tuple of str, optional
        Admin IDs to keep. Defaults to every county in the survey.

    Returns
    -------
    pandas.DataFrame
        One row per surveyed building, carrying the hand-assigned
        ``occupancy_type_canonical``, the pinned ``lat``/``lon``, and the
        parsed ``address_number``/``address_street`` matching keys. Rows
        without a resolved county are dropped: they cannot be linked
        against a county's curated output.
    """
    points = pd.read_csv(GROUND_TRUTH_PATH)
    points = points[points['admin_id'].notna()]
    if counties:
        points = points[points['admin_id'].isin(tuple(counties))]
    return points.reset_index(drop=True)


def collapse_bands(values: pd.Series) -> pd.Series:
    """Map the inventory's Multi-Family height bands onto Multi-Family."""
    return values.astype(object).replace(COLLAPSE)


def source_values(linked: pd.DataFrame) -> dict[str, pd.Series]:
    """The vote and each input it arbitrates, on the survey's vocabulary.

    Parameters
    ----------
    linked : pandas.DataFrame
        Output of :func:`link_ground_truth`.

    Returns
    -------
    dict of str to pandas.Series
        Source label to comparable class values, height bands collapsed.
    """
    values = {
        label: collapse_bands(linked[column])
        for label, column in SOURCE_COLUMNS.items()
        if column in linked.columns
    }
    if OVERTURE_COLUMN in linked.columns:
        dwellings = pd.to_numeric(linked[OVERTURE_COLUMN], errors='coerce')
        values['overture'] = pd.Series(
            [
                'Multi-Family' if n >= 2 else 'Single-Family'
                for n in dwellings.fillna(0)
            ],
            index=linked.index,
            dtype=object,
        )
    return values


def link_ground_truth(
    counties: tuple[str, ...] | None = None,
    *,
    verbose: bool = False,
    save: bool = True,
) -> gpd.GeoDataFrame:
    """Link the survey points to curated footprints, county by county.

    Address identity is tried before proximity (see
    :func:`~openplaces.io.curator.validation.link_points_to_entities`),
    because the nearest footprint to a survey pin is very often a shed or
    the neighbour's house.

    Parameters
    ----------
    counties : tuple of str, optional
        Admin IDs to link. Defaults to :data:`COUNTIES`.
    verbose : bool, optional
        Report per-county linkage counts.
    save : bool, optional
        Write the linked frame to :data:`LINKED_PATH` (parquet, plus a CSV
        sidecar for review). Default True.

    Returns
    -------
    geopandas.GeoDataFrame
        One row per linked point: the survey columns, every curated column
        suffixed ``_inv``, ``matched_by``, and the derived comparison
        columns ``predicted``, ``is_single_dwelling``, ``validation_result``,
        ``occupancy_type_conflict_sources`` and ``sources_disagree``. The
        geometry is the matched footprint, not the survey pin.
    """
    counties = tuple(counties) if counties else COUNTIES
    frames = []
    crs = None
    for admin_id in counties:
        points = load_ground_truth((admin_id,))
        if points.empty:
            continue
        entities = op.get_entities(RECIPE_ID, admin_id, geom=True, missing='ignore')
        if entities is None or entities.empty:
            if verbose:
                print(f'{admin_id}: no curated output on disk, skipped')
            continue
        crs = entities.crs
        # reset_index carries footprint_id through as a column, so the
        # permit notebook can join on an ID that is stable across
        # branches.
        linked = link_points_to_entities(
            points,
            entities.reset_index(),
            max_distance_m=MAX_DIST_M,
            street_threshold=STREET_THRESHOLD,
            admin1_id='US-NC',
            prefer_column=PREFER_COLUMN,
            prefer_values=PREFER_VALUES,
        )
        if linked.empty:
            if verbose:
                print(f'{admin_id}: {len(points)} points, none linked')
            continue
        if verbose:
            by_route = linked['matched_by'].value_counts()
            print(
                f'{admin_id}: {len(linked)}/{len(points)} points linked '
                f'(address {by_route.get("address", 0)}, '
                f'distance {by_route.get("distance", 0)})'
            )
        frames.append(linked)

    if not frames:
        return gpd.GeoDataFrame()

    linked = pd.concat(frames, ignore_index=True)
    linked['predicted'] = collapse_bands(linked['occupancy_type_inv'])
    linked['is_single_dwelling'] = linked['occupancy_type_canonical'].isin(
        SINGLE_DWELLING_CLASSES
    )
    linked['validation_result'] = classify_validation_result(
        linked['occupancy_type_canonical'], linked['predicted']
    )

    sources = source_values(linked)
    linked['occupancy_type_conflict_sources'] = summarize_sources(
        {'ground_truth': linked['occupancy_type_canonical'], **sources}
    )
    # Flag the rows worth reading by hand: any input that spoke and was
    # overruled. Rows where every source agrees need no adjudication.
    disagree = pd.Series(False, index=linked.index)
    for label, values in sources.items():
        if label == 'final_vote':
            continue
        disagree |= values.notna() & values.ne(linked['predicted'])
    linked['sources_disagree'] = disagree

    # link_points_to_entities returns a plain DataFrame, so the matched
    # footprint arrives as a CRS-less object column; restore it from the
    # entities it came from.
    linked = gpd.GeoDataFrame(
        linked.drop(columns='geometry_inv'),
        geometry=gpd.GeoSeries(linked['geometry_inv'], crs=crs),
    )
    if save:
        VALIDATION_DIR.mkdir(parents=True, exist_ok=True)
        linked.to_parquet(LINKED_PATH)
        linked.drop(columns='geometry').to_csv(
            LINKED_PATH.with_suffix('.csv'), index=False
        )
        if verbose:
            print(f'wrote {len(linked)} linked points to {LINKED_PATH}')
    return linked


def score_sources(linked: pd.DataFrame) -> pd.DataFrame:
    """Score the vote and each of its inputs against the survey labels.

    Scoring the inputs alongside the vote is what makes the baseline
    readable: a vote that scores worse than one of its own inputs on a
    class is discarding evidence, which a single-column score cannot show.

    Parameters
    ----------
    linked : pandas.DataFrame
        Output of :func:`link_ground_truth`.

    Returns
    -------
    pandas.DataFrame
        :func:`~openplaces.io.curator.validation.score_classification`
        output for each source, with a leading ``source`` column.
    """
    tables = []
    for label, values in source_values(linked).items():
        table = score_classification(
            linked['occupancy_type_canonical'], values, list(CLASSES)
        )
        table.insert(0, 'source', label)
        tables.append(table)
    return pd.concat(tables, ignore_index=True)
